### ISSUE TITLE
File not marked up for chrome

### ISSUE THREAD

**Issue by freedom1b2830** [archlinuxhardened/selinux#100]
I tried to run chrome, it didn't work, I looked in the logs: an attempt to execute a file for chrome, but it is not marked

see my repo https://github.com/freedom1b2830/TalkAboutSelinux/commit/a8d402b47a9d85d83b4cf72be9d96575470eab93
in this repository I will post similar errors

**Comment by fishilico** [comment]
Hello,
As your report is about a missing policy, it is better to open an issue in upstream refpolicy (as you have also done) than opening on issue here. (If this was about something specific to Arch Linux, this repository would be appropriate).

By the way, if you modified the `chromium` module to include a new context for `chrome_crashpad_handler` in https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/apps/chromium.te and https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/apps/chromium.fc, a Pull Request (to upstream refpolicy) would be appreciated. Otherwise, you would need to wait for some other Chrome/Chromium users to add the required contexts.

I am closing this issue, as it has (already) been forwarded upstream.

Thanks
