### ISSUE TITLE
util-linux-selinux

### ISSUE THREAD

**Issue by RecursiveNature** [archlinuxhardened/selinux#17]
I was able to install a majority of the packages but it stops at a certain point givving me this message:

==> Finished making: util-linux-selinux 2.32-3 (Wed 06 Jun 2018 01:35:16 PM PDT)
loading packages...
warning: libutil-linux-selinux-2.32-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: util-linux-selinux and util-linux-selinux-debug are in conflict

How do I proceed?

**Comment by fishilico** [comment]
By default ``util-linux-selinux`` is built with ``debug`` option, in order to behave like package ``util-linux`` (cf. https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/util-linux&id=17bfbceadddb4ba0745fb5d33936659d619ece42#n16 ). If you do not use it, you would be able to uninstall it (with ``pacman -R util-linux-selinux-debug``). This would solve the package version conflict.

**Comment by RecursiveNature** [comment]
Nevermind... I found a work-around. I did a little commenting out to get around the issue. Thanks.
