### ISSUE TITLE
Is this available in the arch user repo?

### ISSUE THREAD

**Issue by Axilot** [archlinuxhardened/selinux#72]
Hello,
i was wondering if this would be available in the aur, so you can automatically let everything update, when there is something to update.

**Comment by fishilico** [comment]
Hello,
All packages in this repository are available in the AUR (and they can be found by searching the keyword `selinux`: https://aur.archlinux.org/packages/?O=0&SeB=k&K=selinux). In fact, this git repository (https://github.com/archlinuxhardened/selinux) uses git subtrees in order to "share" the git history with the history of AUR packages.
